### ISSUE TITLE
Zelfs zonder classes loopt deze uit geheugen:

### ISSUE THREAD

**Issue by gitpeut** [BobCollinNovi/Lanternfish#1]
Hi Bob,

Mooie oplossing, maar zelfs nu je per vis alleen een item in een arraylist heb gezet haalt hij niet het 'stretch goal' van Arjen dat ie 256 dagen moet halen. Nadat ik het printen eruit had gehaald (dat maakt het allemaal heel traag)   loopt ie er bij mij uit na 210 dagen :-). 

day 210
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3511)
	at java.base/java.util.Arrays.copyOf(Arrays.java:3480)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:454)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at org.peut.Main.main(Main.java:26)

Voor het bewaren van iedere vis moet je aan bestanden gaan denken, omdat je op een normale computer zo'n verschrikkelijke hoeveelheid data niet kwijt kan in het geheugen.
Superleuk te zien hoe iedereen verschillende oplossingen maakt die toch veel op elkaar lijken.

**Comment by BobCollinNovi** [comment]
Hi Jose, dank voor je input!
Ik heb er nog eens even over negdacht en heb een nieuwe oplossing op de team chat gezet, die in mijn java werkt...  Hoop alleen nu dat het resultaat ook klopt :-)

**Comment by gitpeut** [comment]
Goed gedaan Bob!   From: BobCollinNoviSent: donderdag 10 februari 2022 18:21To: BobCollinNovi/LanternfishCc: Jose Baars; AuthorSubject: Re: [BobCollinNovi/Lanternfish] Zelfs zonder classes loopt deze uit geheugen: (Issue #1) Hi Jose, dank voor je input!Ik heb er nog eens even over negdacht en heb een nieuwe oplossing op de team chat gezet, die in mijn java werkt... Hoop alleen nu dat het resultaat ook klopt :-)—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
